// +build !ignore_autogenerated

// Code generated by openapi-gen. DO NOT EDIT.

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/fahlmant/statuspage-operator/pkg/apis/hackday/v1alpha1.StatusPageCustomer":       schema_pkg_apis_hackday_v1alpha1_StatusPageCustomer(ref),
		"github.com/fahlmant/statuspage-operator/pkg/apis/hackday/v1alpha1.StatusPageCustomerSpec":   schema_pkg_apis_hackday_v1alpha1_StatusPageCustomerSpec(ref),
		"github.com/fahlmant/statuspage-operator/pkg/apis/hackday/v1alpha1.StatusPageCustomerStatus": schema_pkg_apis_hackday_v1alpha1_StatusPageCustomerStatus(ref),
		"github.com/fahlmant/statuspage-operator/pkg/apis/hackday/v1alpha1.StatusPageIncident":       schema_pkg_apis_hackday_v1alpha1_StatusPageIncident(ref),
		"github.com/fahlmant/statuspage-operator/pkg/apis/hackday/v1alpha1.StatusPageIncidentSpec":   schema_pkg_apis_hackday_v1alpha1_StatusPageIncidentSpec(ref),
		"github.com/fahlmant/statuspage-operator/pkg/apis/hackday/v1alpha1.StatusPageIncidentStatus": schema_pkg_apis_hackday_v1alpha1_StatusPageIncidentStatus(ref),
	}
}

func schema_pkg_apis_hackday_v1alpha1_StatusPageCustomer(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "StatusPageCustomer is the Schema for the statuspagecustomers API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/fahlmant/statuspage-operator/pkg/apis/hackday/v1alpha1.StatusPageCustomerSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/fahlmant/statuspage-operator/pkg/apis/hackday/v1alpha1.StatusPageCustomerStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/fahlmant/statuspage-operator/pkg/apis/hackday/v1alpha1.StatusPageCustomerSpec", "github.com/fahlmant/statuspage-operator/pkg/apis/hackday/v1alpha1.StatusPageCustomerStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_hackday_v1alpha1_StatusPageCustomerSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "StatusPageCustomerSpec defines the desired state of StatusPageCustomer",
				Properties: map[string]spec.Schema{
					"email": {
						SchemaProps: spec.SchemaProps{
							Description: "INSERT ADDITIONAL SPEC FIELDS - desired state of cluster Important: Run \"operator-sdk generate k8s\" to regenerate code after modifying this file Add custom validation using kubebuilder tags: https://book.kubebuilder.io/beyond_basics/generating_crd.html email clustername components: etcd, registry, api",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"clusterName": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"components": {
						SchemaProps: spec.SchemaProps{
							Type: []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Type:   []string{"string"},
										Format: "",
									},
								},
							},
						},
					},
				},
				Required: []string{"email", "clusterName", "components"},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_hackday_v1alpha1_StatusPageCustomerStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "StatusPageCustomerStatus defines the observed state of StatusPageCustomer",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_hackday_v1alpha1_StatusPageIncident(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "StatusPageIncident is the Schema for the statuspageincidents API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/fahlmant/statuspage-operator/pkg/apis/hackday/v1alpha1.StatusPageIncidentSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/fahlmant/statuspage-operator/pkg/apis/hackday/v1alpha1.StatusPageIncidentStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/fahlmant/statuspage-operator/pkg/apis/hackday/v1alpha1.StatusPageIncidentSpec", "github.com/fahlmant/statuspage-operator/pkg/apis/hackday/v1alpha1.StatusPageIncidentStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_hackday_v1alpha1_StatusPageIncidentSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "StatusPageIncidentSpec defines the desired state of StatusPageIncident",
				Properties: map[string]spec.Schema{
					"startTime": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "date-time",
						},
					},
					"endTime": {
						SchemaProps: spec.SchemaProps{
							Description: "UTC",
							Type:        []string{"string"},
							Format:      "date-time",
						},
					},
					"message": {
						SchemaProps: spec.SchemaProps{
							Description: "UTC",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"type": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
					"components": {
						SchemaProps: spec.SchemaProps{
							Type: []string{"array"},
							Items: &spec.SchemaOrArray{
								Schema: &spec.Schema{
									SchemaProps: spec.SchemaProps{
										Type:   []string{"string"},
										Format: "",
									},
								},
							},
						},
					},
					"name": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
				},
				Required: []string{"startTime", "endTime", "message", "type", "components", "name"},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_hackday_v1alpha1_StatusPageIncidentStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "StatusPageIncidentStatus defines the observed state of StatusPageIncident",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}
