apiVersion: apps/v1
kind: Deployment
metadata:
  name: statuspage-operator1
spec:
  replicas: 1
  selector:
    matchLabels:
      name: statuspage-operator1
  template:
    metadata:
      labels:
        name: statuspage-operator1
    spec:
      serviceAccountName: statuspage-operator1
      containers:
        - name: statuspage-operator1
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - statuspage-operator1
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "statuspage-operator1"
